### ISSUE TITLE
WSS defaults to port 0 on reverse proxy

### ISSUE THREAD

**Issue by mchangrh** [marcopeocchi/yt-dlp-web-ui#100]
Will try to look into it myself, but the WSS defaults to the port path after host - If it is hosted behind a http(s) reverse proxy, there will be no port and this results in the Fetch failing and the application spitting out this error:

```
TypeError: Failed to fetch
    at oy.sendHTTP (https://reverse.example.com/assets/index-aac3ec5e.js:189:12928)
    at oy.freeSpace (https://reverse.example.com/assets/index-aac3ec5e.js:189:13861)
    at get (https://reverse.example.com/assets/index-aac3ec5e.js:189:14412)
    at L (https://reverse.example.com/assets/index-aac3ec5e.js:70:56352)
    at x (https://reverse.example.com/assets/index-aac3ec5e.js:70:57312)
    at https://reverse.example.com/assets/index-aac3ec5e.js:70:58727
    at ie (https://reverse.example.com/assets/index-aac3ec5e.js:70:58515)
    at Object.W [as get] (https://reverse.example.com/assets/index-aac3ec5e.js:70:58720)
    at Kx (https://reverse.example.com/assets/index-aac3ec5e.js:70:14323)
    at lC (https://reverse.example.com/assets/index-aac3ec5e.js:70:16422)
  ```
  
  hostname modified

**Comment by mchangrh** [comment]
I have seen that the localstorage and settings defaults to `reverseproxy` true but I can't reliably recreate it on my machine and instead of soft erroring like previously, it hard crashes to `Unexpected Application Error!` until localsettings is set manually
