### ISSUE TITLE
Unexpected Application Error

### ISSUE THREAD

**Issue by pargit** [marcopeocchi/yt-dlp-web-ui#128]
hi
running on docker windows (wsl2) latest image.
when trying to select format the website crash with this error:
TypeError: Failed to fetch dynamically imported module: http://localhost:3033/assets/ErrorBoundary-73dae622.js
from the docker logs:
`2024-01-12 11:02:12 2024/01/12 09:02:12  Metadata   Formats  https://www.youtube.com/watch?v=OhhOU5FUPBE
2024-01-12 11:02:12 panic: runtime error: invalid memory address or nil pointer dereference
2024-01-12 11:02:12 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x54d878]
2024-01-12 11:02:12 
2024-01-12 11:02:12 goroutine 153 [running]:
2024-01-12 11:02:12 log/slog.(*Logger).Handler(...)
2024-01-12 11:02:12     /usr/local/go/src/log/slog/logger.go:89
2024-01-12 11:02:12 log/slog.(*Logger).Enabled(0xc000306f58?, {0xd19c48?, 0x1159600?}, 0xc000306fa0?)
2024-01-12 11:02:12     /usr/local/go/src/log/slog/logger.go:137 +0x18
2024-01-12 11:02:12 log/slog.(*Logger).log(0x0, {0xd19c48, 0x1159600}, 0x0, {0xaced9a, 0x13}, {0xc000307328, 0x2, 0x2})
2024-01-12 11:02:12     /usr/local/go/src/log/slog/logger.go:210 +0x6a
2024-01-12 11:02:12 log/slog.(*Logger).Info(...)
2024-01-12 11:02:12     /usr/local/go/src/log/slog/logger.go:178
2024-01-12 11:02:12 github.com/marcopeocchi/yt-dlp-web-ui/server/internal.(*Process).GetFormatsSync(0xc0003075c0)
2024-01-12 11:02:12     /usr/src/yt-dlp-webui/server/internal/process.go:243 +0x46b
2024-01-12 11:02:12 github.com/marcopeocchi/yt-dlp-web-ui/server/rpc.(*Service).Formats(0xc000319f20?, {{0x0, 0x0}, {0xc0001128a0, 0x2b}, {0x0, 0x0, 0x0}}, 0xc00011a2c0)
2024-01-12 11:02:12     /usr/src/yt-dlp-webui/server/rpc/service.go:75 +0xe5
2024-01-12 11:02:12 reflect.Value.call({0xc000096840?, 0xc0000943f8?, 0x13?}, {0xac8811, 0x4}, {0xc000104ef8, 0x3, 0x3?})
2024-01-12 11:02:12     /usr/local/go/src/reflect/value.go:596 +0xce7
2024-01-12 11:02:12 reflect.Value.Call({0xc000096840?, 0xc0000943f8?, 0x0?}, {0xc00004fef8?, 0x0?, 0x0?})
2024-01-12 11:02:12     /usr/local/go/src/reflect/value.go:380 +0xb9
2024-01-12 11:02:12 net/rpc.(*service).call(0xc0001c6680, 0x0?, 0x0?, 0xc000013a40, 0xc0000a8b80, 0x0?, {0xa7b980?, 0xc000025a80?, 0x0?}, {0xa13fe0, ...}, ...)
2024-01-12 11:02:12     /usr/local/go/src/net/rpc/server.go:382 +0x211
2024-01-12 11:02:12 created by net/rpc.(*Server).ServeCodec in goroutine 151
2024-01-12 11:02:12     /usr/local/go/src/net/rpc/server.go:479 +0x410
2024-01-12 11:02:13 2024/01/12 09:02:13  config  no config file found
2024-01-12 11:02:13 time=2024-01-12T09:02:13.363Z level=INFO msg="sucessfully persisted session"`

how can i fix it?

thanks

**Comment by marcopeocchi** [comment]
hello @pargit,

It was a regression introduced in #127. Thanks for pointing it out.

**Comment by pargit** [comment]
after pulling latest image everything look fine :)
thanks
