### ISSUE TITLE
[BUG] Latest image does not include yt-dlp

### ISSUE THREAD

**Issue by CrazyWolf13** [marcopeocchi/yt-dlp-web-ui#217]
**Version running**
latest

**Describe the bug**
When running the latest image released 6 days ago, I cannot run any downloads, because there is no yt-dlp apparently:

**To Reproduce**
1. Update to new latest
2. Try a download
3. See no yt-dlp
4. See error in log

**Expected behavior**
I expect it to download videos.

**Screenshots**

**Additional context**
Docker Logs:
```
time=2024-11-02T14:26:11.946Z level=INFO msg="yt-dlp-webui started" address=0.0.0.0:3033
time=2024-11-02T14:26:36.613Z level=INFO msg="detaching from logger"
time=2024-11-02T14:26:44.439Z level=INFO msg="received process from event bus" bus=process:pending consumer=metadataConsumer id=1a85b347
time=2024-11-02T14:26:44.439Z level=INFO msg="received process from event bus" bus=process:pending consumer=downloadConsumer id=1a85b347
time=2024-11-02T14:26:44.439Z level=INFO msg="started process" bus=process:pending id=1a85b347
time=2024-11-02T14:26:44.439Z level=INFO msg="requesting download" url="https://www.youtube.com/watch?v=MMqIjlvNCyw" params="[https://www.youtube.com/watch?v=MMqIjlvNCyw --newline --no-colors --no-playlist --progress-template download:{\"eta\":%(progress.eta)s,\"percentage\":\"%(progress._percent_str)s\",\"speed\":%(progress.speed)s} --progress-template postprocess:{\"filepath\":\"%(info.filepath)s\"} -o /downloads/%(title)s.%(ext)s]"
time=2024-11-02T14:26:44.440Z level=ERROR msg="failed to retrieve metadata" id=1a85b347 err="fork/exec /usr/local/bin/yt-dlp: no such file or directory"
time=2024-11-02T14:26:44.440Z level=ERROR msg="failed to start yt-dlp process" err="fork/exec /usr/local/bin/yt-dlp: no such file or directory"
panic: fork/exec /usr/local/bin/yt-dlp: no such file or directory
goroutine 142 [running]:
github.com/marcopeocchi/yt-dlp-web-ui/server/internal.(*Process).Start(0xc0002214a0)
	/usr/src/yt-dlp-webui/server/internal/process.go:129 +0xd4a
github.com/marcopeocchi/yt-dlp-web-ui/server/internal.(*MessageQueue).downloadConsumer.func1(0xc0002214a0)
	/usr/src/yt-dlp-webui/server/internal/message_queue.go:74 +0x40e
reflect.Value.call({0xaa5c20?, 0xc000245b70?, 0x13?}, {0xb57998, 0x4}, {0xc000126258, 0x1, 0x1?})
	/usr/local/go/src/reflect/value.go:581 +0xca6
reflect.Value.Call({0xaa5c20?, 0xc000245b70?, 0xc000423690?}, {0xc000126258?, 0x0?, 0x0?})
	/usr/local/go/src/reflect/value.go:365 +0xb9
github.com/asaskevich/EventBus.(*EventBus).doPublish(0x0?, 0xc000280750, {0x0?, 0x0?}, {0xc000423690?, 0x0?, 0x0?})
	/go/pkg/mod/github.com/asaskevich/!event!bus@v0.0.0-20200907212545-49d423059eef/event_bus.go:160 +0x4d
github.com/asaskevich/EventBus.(*EventBus).doPublishAsync(0x0?, 0x0?, {0xb5bd79?, 0x74ecc8?}, {0xc000423690?, 0xde5918?, 0xc00050e840?})
	/go/pkg/mod/github.com/asaskevich/!event!bus@v0.0.0-20200907212545-49d423059eef/event_bus.go:168 +0x92
created by github.com/asaskevich/EventBus.(*EventBus).Publish in goroutine 140
	/go/pkg/mod/github.com/asaskevich/!event!bus@v0.0.0-20200907212545-49d423059eef/event_bus.go:152 +0x565
time=2024-11-02T14:26:45.177Z level=INFO msg="yt-dlp-webui started" address=0.0.0.0:3033
```

**Comment by CrazyWolf13** [comment]
Temporary workaround, as yt-dlp installs to `/usr/bin/yt-dlp` while yt-dlp-web-ui expects `/usr/local/bin/yt-dlp`
```bash
ln -s /usr/bin/yt-dlp /usr/local/bin/yt-dlp
```

**Comment by marcopeocchi** [comment]
I'm not surprised with Alpine Linux anymore...
Apparently `/usr/local/bin` is not in PATH.

**Comment by marcopeocchi** [comment]
@CrazyWolf13 I think it can be marked as solved (??). I've pulled the latest container and the issue seems solved.

**Comment by marcopeocchi** [comment]
Hi @CrazyWolf13,

v3.2.2 came out, did you get a chance to try it out?

**Comment by CrazyWolf13** [comment]
@marcopeocchi  I just repulled the latest tag and tried again, the error with the no such file persists, also the yt-dlp version does still not show:

![grafik](https://github.com/user-attachments/assets/b78dff12-0a3b-4662-a790-fd439cdfdd8d)
![grafik](https://github.com/user-attachments/assets/7ed72370-b994-4692-b183-85d7cf99af47)

**Comment by marcopeocchi** [comment]
Are you using a configuration file? If so, may you paste it here?

**Comment by CrazyWolf13** [comment]
Sure, but I did not change anything there, is after an update a chnage of the base downloader path needed, which I missed?

```

# Simple configuration file for yt-dlp webui

---
# Host where server will listen at (default: "0.0.0.0")
#host: 0.0.0.0

# Port where server will listen at (default: 3033)
port: 3033

# Directory where downloaded files will be stored (default: ".")
downloadPath: /downloads

# [optional] The download queue size (default: 8)
queue_size: 8

# [optional] Full path to the yt-dlp (default: "yt-dlp")
downloaderPath: /usr/local/bin/yt-dlp

# [optional] Directory where the log file will be stored (default: ".")
log_path: /config

# [optional] Directory where the session database file will be stored (default: ".")
session_file_path: /config

# OpenID Google Oauth2 example

# disable password based authentication
require_auth: false
username: *****
password: *****

# enable openid authentification
use_openid: true
openid_provider_url: https://auth.mydomain.dev/application/o/ytdlp/
openid_client_id: ******
openid_client_secret: *******

# localhost:3033 is where yt-dlp-webui is exposed
openid_redirect_url: https://ytdlp.mydomain.dev/auth/openid/signin
# a production like example
# openid_redirect_url: https://yt-dlp-webui.yourdomain.tld/auth/openid/signin
```

**Comment by marcopeocchi** [comment]
@CrazyWolf13 remove this line `downloaderPath: /usr/local/bin/yt-dlp`

**Comment by marcopeocchi** [comment]
yt-dlp is already shipped with the container.

**Comment by CrazyWolf13** [comment]
Awesome!
Yup that fixed the issue!

Yeah updating the readme would be a good idea :)
